### ISSUE TITLE
Single click event setting

### ISSUE THREAD

**Issue by vjetname** [TatuLund/GridFastNavigation#26]
Hi,
first, thanks for great addon.
I have some spectial requiriments for grid component.
I found double click for opening editor useful, because I use selection in the grid.
Could please make the "single click to open editor" feature optional?

I'm using GridFastNavigation version 0.5.6 for Vaadin 7.7.7.
Thank you for response.
Milan

**Comment by TatuLund** [comment]
Adding API to control this should be easy to implement, I will check this after we have released the Vaadin8 version.

**Comment by TatuLund** [comment]
Change is included in version 0.5.7

**Comment by vjetname** [comment]
Hi, thanks for your effort, but I still have an issue with editor opening on single click - even if I do set the property like
nav.setOpenEditorWithSingleClick(false);
Do you have an idea what is wrong?
Thank you,
Milan

**Comment by TatuLund** [comment]
Did you remember to recompile the widgetset?

**Comment by vjetname** [comment]
I'm quite sure I did, but today I tried it once more and now it works pretty well, so it's alrigth, thank you very much.
